# Generated by Django 3.2 on 2021-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20200609_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.AddField(
            model_name='response',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User_ID'),
        ),
    ]
