# Generated by Django 3.2 on 2021-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20210615_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='redirect_on_success',
            field=models.CharField(default='', max_length=64, verbose_name='Redirect of success'),
        ),
    ]
