# Generated by Django 3.2 on 2021-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_survey_redirect_on_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='redirect_on_success',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Redirect of success'),
        ),
    ]
