# Generated by Django 5.2.15 on 2026-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_css_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='scale_min',
            field=models.IntegerField(blank=True, help_text='range of possible answers', null=True, verbose_name='Scale minimum'),
        ),
    ]
