# Generated by Django 6.1.1 on 2026-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_question_text_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='other_option',
            field=models.BooleanField(default=False, verbose_name="Add an 'other' free-text option"),
        ),
        migrations.AlterField(
            model_name='question',
            name='will_not_answer_option',
            field=models.BooleanField(default=False, verbose_name="Add a 'will not answer' option"),
        ),
    ]
