# Generated by Django 6.1.1 on 2026-09-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_alter_question_other_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group_header',
            field=models.BooleanField(default=True, help_text='Show the header-only fields: header rows, row label and answer-label hiding.', verbose_name='Group header'),
        ),
        migrations.AddField(
            model_name='question',
            name='hide_answer_labels',
            field=models.BooleanField(default=False, help_text="Do not show the label next to each answer option of this question's group; header rows can label the options instead.", verbose_name='Hide answer labels'),
        ),
    ]
