# Generated by Django 6.1.1 on 2026-10-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_question_group_header_question_hide_answer_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden from participants'),
        ),
    ]
