# Generated by Django 5.2.15 on 2026-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_category_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
