# Generated by Django 5.2.15 on 2026-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_alter_survey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='will_not_answer_label',
            field=models.CharField(blank=True, default='I will not answer', max_length=200, verbose_name="Label for the 'will not answer' option"),
        ),
    ]
