# Generated by Django 5.2.15 on 2026-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_alter_question_will_not_answer_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hide_answer_labels',
            field=models.BooleanField(default=False, help_text='Every question of this group offers the same answer options, so one set of labels describes them all. A wide screen shows that set once, in the header rows; a narrow screen shows it next to each answer option instead.', verbose_name='Shared answer labels'),
        ),
    ]
